name: Build All Platforms

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Tkinter (Linux only)
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y python3-tk

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pyinstaller

    - name: Build executable with PyInstaller (Windows)
      if: runner.os == 'Windows'
      run: |
        pyinstaller --noconfirm --onefile --add-data "assets;assets" --add-data "langs;langs" main.py

    - name: Build executable with PyInstaller (Linux/Mac)
      if: runner.os != 'Windows'
      run: |
        pyinstaller --noconfirm --onefile --add-data "assets:assets" --add-data "langs:langs" main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-${{ runner.os }}
        path: dist/